import Tile from "./Tile";
import { ImageSourcePropType } from "react-native/types";

export const TilesArray = {
	BLANK: ["BLANK", 0, require("../../../resources/images/sharp-tiles/BLANK.jpg")],
	A: ["A", 1, require("../../../resources/images/sharp-tiles/A.jpg")],
	B: ["B", 3, require("../../../resources/images/sharp-tiles/B.jpg")],
	C: ["C", 3, require("../../../resources/images/sharp-tiles/C.jpg")],
	D: ["D", 2, require("../../../resources/images/sharp-tiles/D.jpg")],
	E: ["E", 1, require("../../../resources/images/sharp-tiles/E.jpg")],
	F: ["F", 4, require("../../../resources/images/sharp-tiles/F.jpg")],
	G: ["G", 2, require("../../../resources/images/sharp-tiles/G.jpg")],
	H: ["H", 4, require("../../../resources/images/sharp-tiles/H.jpg")],
	I: ["I", 1, require("../../../resources/images/sharp-tiles/I.jpg")],
	J: ["J", 8, require("../../../resources/images/sharp-tiles/J.jpg")],
	K: ["K", 5, require("../../../resources/images/sharp-tiles/K.jpg")],
	L: ["L", 1, require("../../../resources/images/sharp-tiles/L.jpg")],
	M: ["M", 3, require("../../../resources/images/sharp-tiles/M.jpg")],
	N: ["N", 1, require("../../../resources/images/sharp-tiles/N.jpg")],
	O: ["O", 1, require("../../../resources/images/sharp-tiles/O.jpg")],
	P: ["P", 3, require("../../../resources/images/sharp-tiles/P.jpg")],
	Q: ["Q", 10, require("../../../resources/images/sharp-tiles/Q.jpg")],
	R: ["R", 1, require("../../../resources/images/sharp-tiles/R.jpg")],
	S: ["S", 1, require("../../../resources/images/sharp-tiles/S.jpg")],
	T: ["T", 1, require("../../../resources/images/sharp-tiles/T.jpg")],
	U: ["U", 1, require("../../../resources/images/sharp-tiles/U.jpg")],
	V: ["V", 4, require("../../../resources/images/sharp-tiles/V.jpg")],
	W: ["W", 4, require("../../../resources/images/sharp-tiles/W.jpg")],
	X: ["X", 8, require("../../../resources/images/sharp-tiles/X.jpg")],
	Y: ["Y", 4, require("../../../resources/images/sharp-tiles/Y.jpg")],
	Z: ["Z", 10, require("../../../resources/images/sharp-tiles/Z.jpg")],
};

const Tiles = {
	BLANK: new Tile("BLANK", 0, require("../../../resources/images/sharp-tiles/BLANK.jpg")),
	A: new Tile("A", 1, require("../../../resources/images/sharp-tiles/A.jpg")),
	B: new Tile("B", 3, require("../../../resources/images/sharp-tiles/B.jpg")),
	C: new Tile("C", 3, require("../../../resources/images/sharp-tiles/C.jpg")),
	D: new Tile("D", 2, require("../../../resources/images/sharp-tiles/D.jpg")),
	E: new Tile("E", 1, require("../../../resources/images/sharp-tiles/E.jpg")),
	F: new Tile("F", 4, require("../../../resources/images/sharp-tiles/F.jpg")),
	G: new Tile("G", 2, require("../../../resources/images/sharp-tiles/G.jpg")),
	H: new Tile("H", 4, require("../../../resources/images/sharp-tiles/H.jpg")),
	I: new Tile("I", 1, require("../../../resources/images/sharp-tiles/I.jpg")),
	J: new Tile("J", 8, require("../../../resources/images/sharp-tiles/J.jpg")),
	K: new Tile("K", 5, require("../../../resources/images/sharp-tiles/K.jpg")),
	L: new Tile("L", 1, require("../../../resources/images/sharp-tiles/L.jpg")),
	M: new Tile("M", 3, require("../../../resources/images/sharp-tiles/M.jpg")),
	N: new Tile("N", 1, require("../../../resources/images/sharp-tiles/N.jpg")),
	O: new Tile("O", 1, require("../../../resources/images/sharp-tiles/O.jpg")),
	P: new Tile("P", 3, require("../../../resources/images/sharp-tiles/P.jpg")),
	Q: new Tile("Q", 10, require("../../../resources/images/sharp-tiles/Q.jpg")),
	R: new Tile("R", 1, require("../../../resources/images/sharp-tiles/R.jpg")),
	S: new Tile("S", 1, require("../../../resources/images/sharp-tiles/S.jpg")),
	T: new Tile("T", 1, require("../../../resources/images/sharp-tiles/T.jpg")),
	U: new Tile("U", 1, require("../../../resources/images/sharp-tiles/U.jpg")),
	V: new Tile("V", 4, require("../../../resources/images/sharp-tiles/V.jpg")),
	W: new Tile("W", 4, require("../../../resources/images/sharp-tiles/W.jpg")),
	X: new Tile("X", 8, require("../../../resources/images/sharp-tiles/X.jpg")),
	Y: new Tile("Y", 4, require("../../../resources/images/sharp-tiles/Y.jpg")),
	Z: new Tile("Z", 10, require("../../../resources/images/sharp-tiles/Z.jpg")),
};

export default Tiles;
